# config

datadir: '/s/project/gene_embedding'

SELECT_TRAITS:
    GWAS:
        - "Alanine_aminotransferase"
        - "Cholesterol"
        - "IGF_1"
        - "Albumin"
        - "LDL_direct"
        - "Alkaline_phosphatase"
        - "C_reactive_protein"
        - "Total_protein"
        - "Apolipoprotein_A"
        - "Creatinine"
        - "Triglycerides"
        - "Apolipoprotein_B"
        - "Mean_corpuscular_haemoglobin"
        - "Phosphate"
        - "Body_mass_index__BMI_"
        - "HDL_cholesterol"
        - "SHBG" 
        - "Urea"
        - "Gamma_glutamyltransferase"
        - "Glycated_haemoglobin__HbA1c_"
        - "Vitamin_D"
        - "Calcium_30680"        
    GENEBASS:
        - "Mean_corpuscular_haemoglobin" 
        - "Mean_sphered_cell_volume" 
        - "Red_blood_cell_(erythrocyte)_distribution_width"
        - "Glycated_haemoglobin_(HbA1c)"
        - "Red_blood_cell_(erythrocyte)_count"
        - "Reticulocyte_count"
        - "Platelet_distribution_width"
        - "Mean_platelet_(thrombocyte)_volume"
        - "Platelet_count"
        - "Lymphocyte_count"
        - "Monocyte_count"
        - "Eosinophill_count"
        - "Lymphocyte_percentage"
        - "Neutrophill_count"
        - "Sitting_height"
        - "Standing_height"
        - "Forced_expiratory_volume_in_1-second_(FEV1),_predicted"
        - "Whole_body_fat-free_mass"
        - "Forced_vital_capacity_(FVC)"
        - "Frequency_of_inability_to_cease_drinking_in_last_year"
        - "Frequency_of_memory_loss_due_to_drinking_alcohol_in_last_year"
        - "Frequency_of_failure_to_fulfil_normal_expectations_due_to_drinking_alcohol_in_last_year"
        - "Recent_changes_in_speed/amount_of_moving_or_speaking"
        - "Cholesterol"
        - "HDL_cholesterol"
        - "Triglycerides"
        - "Alkaline_phosphatase"
        - "Gamma_glutamyltransferase"
        - "Creatinine"
        - "Cystatin_C"
        - "Urate"
        - "SHBG"
        - "IGF-1"
        - "Total_bilirubin"
